language: swift
osx_image: xcode10.1

notifications:
  email:
    - pettitude.app@gmail.com

before_install:
  - cp Pettitude/Resources/Config/Mock/mock-GoogleService-Info.plist Pettitude/Resources/Config/Release/GoogleService-Info.plist
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
  - bundle install
  - bundle exec pod install --repo-update
    
script:
  - set -o pipefail
  - xcodebuild -workspace Pettitude.xcworkspace -scheme Pettitude -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - swiftlint


